---
# Adding plugins: https://pre-commit.com/#plugins

repos:

  # general linting
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
        exclude: '^assets/fonts/fontawesome-webfont.svg$'
      - id: end-of-file-fixer
        exclude: '^CNAME$'
      - id: mixed-line-ending
        args: ['--fix=lf']
        description: Forces to replace line ending by the UNIX 'lf' character.

  # markdown linting
  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.13.0
    hooks:
      - id: markdownlint
        entry: mdl --style .markdownlint.rb

  # Modern CSS linting
  - repo: https://github.com/thibaudcolas/pre-commit-stylelint
    rev: v16.26.1
    hooks:
      - id: stylelint
        files: assets/css/custom/.*\.css$
        additional_dependencies:
          - stylelint
          - stylelint-config-standard
        args: [--fix]

  # JavaScript linting
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.39.1
    hooks:
      - id: eslint
        files: assets/js/custom/.*\.js$
        types: [file]
        additional_dependencies:
          - eslint
          - eslint-config-standard
          - eslint-plugin-import
          - eslint-plugin-node
          - eslint-plugin-n
          - eslint-plugin-promise
          - '@eslint/eslintrc'
          - globals

  # Universal Formatter
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or: [css, javascript, html, json]
        files: 'custom/.*\.(css|js|json)$|^index.html$'

  # YAML linting
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
        entry: yamllint -c .yamllint.yaml .
