---
name: lint

on:
  pull_request:
    branches: [gh-pages]  # gh-pages branches is my default branch

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pre-commit/action@v3.0.0
